#!/bin/sh
#docker run -it --rm -w /root/lidar_ws --device /dev/teensy12345 -v ~/lidar_ws:/root/lidar_ws brianerickson/ros bash
docker run -it --rm -w /root/lidar_ws --privileged --name car -v /dev/teensy12345:/dev/teensy12345 -v ~/lidar_ws:/root/lidar_ws brianerickson/ros bash
