Header header

uint32 ms
uint32 us
float32 v_bat
string mode

float32 rx_str
float32 rx_esc
float32 ax
float32 ay
float32 az
uint32 spur_us
int32 spur_odo
int32 odo_fl_a
uint32 odo_fl_a_us
int32 odo_fl_b
uint32 odo_fl_b_us
uint32 odo_fl_ab_us
int32 odo_fr_a
uint32 odo_fr_a_us
int32 odo_fr_b
uint32 odo_fr_b_us
uint32 odo_fr_ab_us

float32 mpu_deg_yaw
float32 mpu_deg_pitch
float32 mpu_deg_roll
float32 mpu_deg_f
bool go